name: beltofdestiny
description: 'Save the world, or recycle it.'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  go_router: ^13.0.1
  flame: ^1.14.0
  flame_audio: ^2.1.7
  logger: ^2.0.2+1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  nes_ui: ^0.15.0
  provider: ^6.1.1
  flutter_animate: ^4.4.0
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

fonts:
  - family: 'ArcadeYA'
    fonts:
      - asset: 'assets/fonts/arcade_ya/ARCADE_I.TTF'
        style: italic
      - asset: 'assets/fonts/arcade_ya/ARCADE_N.TTF'

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/app_icon/placeholder.png'
  mac:
    generate: true
    image_path: 'assets/app_icon/placeholder.png'
  web:
    generate: true
    image_path: 'assets/app_icon/placeholder.png'
    background_color: '#14452F'
    theme_color: '#14452F'
  windows:
    generate: true
    image_path: 'assets/app_icon/placeholder.png'
