// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdBVGV5eR1rfO8xxp-YNSbCKdUqNRASCU',
    appId: '1:613405729311:web:19a60d4f0086763c76ab2a',
    messagingSenderId: '613405729311',
    projectId: 'beltofdestiny',
    authDomain: 'beltofdestiny.firebaseapp.com',
    storageBucket: 'beltofdestiny.appspot.com',
    measurementId: 'G-5P2EN589B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm2-wgnkWoY4rB3rc_J24xeiwz77BU7io',
    appId: '1:613405729311:android:d7d883a74233020b76ab2a',
    messagingSenderId: '613405729311',
    projectId: 'beltofdestiny',
    storageBucket: 'beltofdestiny.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9iCI2WEacT232G63Ea0wPOYl8MwctPc',
    appId: '1:613405729311:ios:b72fa372a8d4961e76ab2a',
    messagingSenderId: '613405729311',
    projectId: 'beltofdestiny',
    storageBucket: 'beltofdestiny.appspot.com',
    iosBundleId: 'com.example.beltofdestiny',
  );
}
